//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string vin { get; set; }
        public string model { get; set; }
        public string mark { get; set; }
        public string color { get; set; }
        public string gos_nomer { get; set; }
        public Nullable<int> trip { get; set; }
        public string ptc_nom { get; set; }
    }
}
