//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holder
    {
        public string vin { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public string city { get; set; }
        public string telephone { get; set; }
        public string mail { get; set; }
    }
}
